spring.application.name=flowpay

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appointments-flowpay}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:flowpay}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:flowpay}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.default-property-inclusion=non_null
server.error.include-stacktrace=never

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
